# Generated by Django 4.0.3 on 2022-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_fertilizer_fert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='fert_date',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='fertilize_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
