# Generated by Django 4.0.3 on 2022-05-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fertservice_remove_fertilizer_fertilize_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FertService',
        ),
    ]
