# Generated by Django 4.0.3 on 2022-05-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer',
            old_name='date',
            new_name='fert_date',
        ),
        migrations.AlterField(
            model_name='plant',
            name='fertilizers',
            field=models.ManyToManyField(blank=True, to='main_app.fertilizer'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
